name: check and mirror

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  EXECUTABLES: "raytracer"

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v4
      - name: check_presence_of_pushed_executables
        run: |
          if [ -z "$EXECUTABLES" ]; then
            echo "No executable to check"
            exit 0
          fi
          for executable in $EXECUTABLES; do
            if [ ! -f $executable ]; then
              echo "No executables are pushed! Good!"
              exit 0
            else
              echo "Executables are pushed! BAD!!!"
              exit 1
            fi
          done
      - name: make_program
        run: make
        timeout-minutes: 2
      - name: make_clean
        run: make clean
      - name: check_presence_of_executables
        run: |
          if [ -z "$EXECUTABLES" ]; then
            echo "No executable to check"
            exit 0
          fi
          for executable in $EXECUTABLES; do
            if [ ! -x $executable ]; then
              echo "Executable : $executable not found"
              exit 1
            fi
          done

  check_coding_style:
    needs: [check_program_compilation]
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - name : check_coding_style
        run: check.sh $(pwd) $(pwd)
        #redirect to a specific line in a file when a Github Actions is clicked
        # so we need to include the file name, the line number and the error message
        # as this example : echo "::error file=path/to/file.cpp,line=42::Error message"
        # if the file is empty (no coding style error) then we print a notice and continue the workflow
        # if the file is not empty (coding style error) then we print an error and stop the workflow
      - name: Anotation of the coding style
        run: |
          cat coding-style-reports.log | while read line; do
            echo "::error file=$(echo $line | cut -d ':' -f 1),\
            line=$(echo $line | cut -d ':' -f 2),\
            title=$(echo $line | cut -d ':' -f 3)"\
            coding style error::"$(echo $line | cut -d ':' -f 4)"
          done
          if [ -s coding-style-reports.log ]; then
            exit 1
          else
            echo "::notice::No coding style error found."
          fi

  run_tests:
    needs: [check_program_compilation]
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: run_tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    if: ${{ github.event_name == 'push' }}
    needs: [check_program_compilation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}